# Evaluate SCHOLAR results

In [36]:
# yelp | booking 
dataset = "booking"

In [37]:
import os, sys, scipy, json
from scipy import sparse
import codecs
import numpy as np
import pandas as pd
import file_handling as fh
from sklearn.model_selection import train_test_split

In [38]:
if sys.platform == "darwin":
    pass
else:
    input_dir = "/nfs/home/maxa/results/"+dataset+'/scholar/'
        
print(input_dir)
#try:
#    os.mkdir(output_dir)
#except:
#pass

/nfs/home/maxa/results/booking/scholar/

In [39]:
if dataset == "booking":
    input_dir = input_dir + "old_topic_wordering/"

In [40]:
print(len(os.listdir(input_dir)))
os.listdir(input_dir)

8

['w_intercept', 'k_200', 'k_30', 'k_150', 'k_20', 'k_10', 'k_100', 'k_50']

In [41]:
if dataset == 'booking':
    ks = ['k_200', 'k_30', 'k_150', 'k_20', 'k_10', 'k_100', 'k_50']
elif dataset == 'yelp':
    ks = ['k200', 'k30', 'k150', 'k20', 'k10', 'k100', 'k50']

In [42]:
pR = pd.DataFrame()
mse = pd.DataFrame()
pplxy = pd.DataFrame()
for k in ks:
    pRs = []
    mses = []
    pplxies = []
    runs_dir = input_dir + k
    for run in os.listdir(runs_dir):
        pRs.append(pd.read_csv(os.path.join(runs_dir,run,'test_eval_pR2.txt'),
                               header = None).values[0][0])
        mses.append(pd.read_csv(os.path.join(runs_dir,run,'test_eval_mse.txt'),
                               header = None).values[0][0])
        pplxies.append(pd.read_csv(os.path.join(runs_dir,run,'test_eval_perplexity.txt'),
                               header = None).values[0][0]) 
    pR = pd.concat([pR,pd.DataFrame(pRs, columns=[k])], ignore_index=True, axis=1)
    mse = pd.concat([mse,pd.DataFrame(mses, columns=[k])], ignore_index=True, axis=1)
    pplxy = pd.concat([pplxy,pd.DataFrame(pplxies, columns=[k])], ignore_index=True, axis=1)
pR.columns = ks
mse.columns = ks
pplxy.columns = ks

In [43]:
pr_stats = pR.describe().T
pr_stats[["mean",'std']]

           mean       std
k_200  0.378978  0.042709
k_30   0.494797  0.002571
k_150  0.484798  0.002750
k_20   0.495444  0.003129
k_10   0.493897  0.004791
k_100  0.489331  0.002454
k_50   0.493856  0.003874

In [44]:
pr_stats[["mean",'std']].to_latex()

'\\begin{tabular}{lrr}\n\\toprule\n{} &      mean &       std \\\\\n\\midrule\nk\\_200 &  0.378978 &  0.042709 \\\\\nk\\_30  &  0.494797 &  0.002571 \\\\\nk\\_150 &  0.484798 &  0.002750 \\\\\nk\\_20  &  0.495444 &  0.003129 \\\\\nk\\_10  &  0.493897 &  0.004791 \\\\\nk\\_100 &  0.489331 &  0.002454 \\\\\nk\\_50  &  0.493856 &  0.003874 \\\\\n\\bottomrule\n\\end{tabular}\n'

In [45]:
pplxy_stats = pplxy.describe().T
pplxy_stats[["mean",'std']].astype(int)

                      mean                  std
k_200 -9223372036854775808 -9223372036854775808
k_30                  2110                  396
k_150               223516               173745
k_20                  1420                  163
k_10                   941                  134
k_100                31601                19590
k_50                  5014                 1314

In [130]:
pplxy.astype(int)

                  k_200  k_30            k_150  k_20  k_10   k_100  k_50
0                 97523  2177            64363  1612   906   27625  4674
1                 34845  1767           133553  1471   872   28566  5737
2                480058  1773           132781  1337   962   17278  6606
3                 29364  2360           429083  1197  1008   20274  5889
4                 96082  3378           280573  1336   743   32060  3857
5                278056  2243           172696  1496   990   23835  4557
6               1347949  2054           160046  1455   963   26836  3668
7                  5245  2110           249455  1808   936   26729  4206
8                 33428  1952           254675  1432  1211   23734  6297
9                189466  1546            84627  1401   714  100777  7500
10              2575175  2054           177009  1257   829   21753  4193
11               315199  1713           324928  1427   830   47211  8114
12                 3854  2769  529087131128767  1435  1052   58464  4066
13             15881231  2239           378307  1302  1127   16921  3651
14               101908  1876           145132  1407   837   23867  5778
15 -9223372036854775808  1963            99278  1380   959   17761  3718
16       76916653024575  2164           154322  1648   726   40486  4185
17                 4448  2022           178958  1418  1087   20521  4027
18               691830  2045           116052  1043  1024   39414  4792
19                81483  1990           830379  1529  1038   17917  4757

# Top words

In [171]:
if dataset == 'booking':
    ks = ['k_30', 'k_20', 'k_10', 'k_100', 'k_50']
elif dataset == 'yelp':
    ks = ['k30', 'k20', 'k10', 'k100', 'k50']

In [166]:
n_topwords = 10
example_run = 10

In [190]:
k = "k_10"
runs_dir = input_dir + k
run = runs_dir[0]
for k in ks:
    runs_dir = input_dir + k
    run = os.listdir(runs_dir)[example_run]
    os.path.join(runs_dir,run,'/topics.txt')
    pd.read_csv(os.path.join(runs_dir,run,'topics.txt'), header = None)

In [194]:
runs_dir + run

'/nfs/home/maxa/results/booking/scholar/k_50k50_ep200_run_12'

In [197]:
pd.read_csv(os.path.join(runs_dir,run,'topics.txt'), header = None)

                                                    0
0   refurbish worn furnitur carpet renov corridor ...
1   noisi nois condit air loud unit neighbor awak ...
2   channel tv news english nespresso comput equip...
3   tea coffe kettl machin maker spotless pod faci...
4   loung tabl bar queue waiter drink relax seat w...
5   bacon egg scrambl bread sausag toast omelett f...
6   slope slipperi socket mood lamp bedsid shelf s...
7   car park public metrono hyde transport garag p...
8   phone data tv mobil speaker awesom devic elect...
9   recommand twice housekeep insist knock excus i...
10  excellentno serviceno class com outstand relat...
11  comfort extrem clean veri friendli modern equi...
12  hop subway bu metro district main cathedr stat...
13  effici delici egg profession varieti choic sel...
14  definit againno recommend back longer highli w...
15  swim gym transport public aldgat drain tear po...
16  worst dirti furnitur poor terribl unfriendli s...
17  dirti smell bad uncomfort noisi broken toilet ...
18  lift stair carri signal slow difficult fi wi w...
19  great atmospher superb love amaz fab small hot...
20  birthday cake celebr anniversari balloon speci...
21  court earl paddington heathrow togeth singl su...
22  distanc notr dame louvr within attract covent ...
23  helpfulno staffno friendlyno friendli excel he...
24  airport shuttl euro taxi bu cost includ buffet...
25  moneyno valu money highli recommend class anyo...
26  hair dryer soap knock shampoo gel cup maid tow...
27  center centr far tram citi beach ride bicycl a...
28  stationno nord gare traffic lyon train access ...
29  wi fi connect internet weak signal wifi speed ...
30  credit deposit card payment account refund amo...
31  everyth perfect everi perfectno greatno thingn...
32  wardrob slide closet privaci smallest mattress...
33  valu noth money excel fantast everyth servic d...
34  everythingno comfyno pillow locationno soft ma...
35  comfi rooftop roof eiffel super poolno pool vi...
36  locationno breakfastno great roomno nice good ...
37  buckingham hyde kensington albert tube theatr ...
38  pressur comfi shower wet bathtub head water mi...
39  rooftop roof pool swim terrac gym gothic spa f...
40  histor interior build th uniqu stun canal spec...
41  alarm condit air fire condition fix heater mai...
42  poor ventil televis con roof tile pool air gym...
43  smoke cigarett smell photo smaller star pictur...
44  troubl noth ever dislik world cleanli best abs...
45  horribl worst unfriendli rude custom ever mous...
46  transport public attract distanc local within ...
47  earli flight readi pm birthday check earlier o...
48  twin doubl superior singl king com book smalle...
49  team moment name royalti youno hospit concierg...

FileNotFoundError: [Errno 2] No such file or directory: '/topics.txt'

In [166]:
pR = pd.DataFrame()
mse = pd.DataFrame()
pplxy = pd.DataFrame()
for k in ks:
    topwords = []
    runs_dir = input_dir + k
    for run in os.listdir(runs_dir):
        pRs.append(pd.read_csv(os.path.join(runs_dir,run,'topics.txt'),
                               header = None).values[0][0])
        mses.append(pd.read_csv(os.path.join(runs_dir,run,'test_eval_mse.txt'),
                               header = None).values[0][0])
        pplxies.append(pd.read_csv(os.path.join(runs_dir,run,'test_eval_perplexity.txt'),
                               header = None).values[0][0]) 
    pR = pd.concat([pR,pd.DataFrame(pRs, columns=[k])], ignore_index=True, axis=1)
    mse = pd.concat([mse,pd.DataFrame(mses, columns=[k])], ignore_index=True, axis=1)
    pplxy = pd.concat([pplxy,pd.DataFrame(pplxies, columns=[k])], ignore_index=True, axis=1)
pR.columns = ks
mse.columns = ks
pplxy.columns = ks

FileNotFoundError: [Errno 2] No such file or directory: '/nfs/home/maxa/results/booking/scholar/k_200/k200_ep200_run_8/topics.txt'

In [167]:
input_dir + k

'/nfs/home/maxa/results/booking/scholar/k_200'

In [169]:
k = "k_10"

In [170]:
k

'k_10'

#